spring:
  application:
    name: product-service
  profiles:
    group:
      "memory": "memory"
    active: memory

---
spring:
  config:
    activate:
      on-profile: "memory"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:./db/h2/schema.sql
      data-locations: classpath:./db/h2/data.sql

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework.security: debug

---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:./db/h2/schema.sql
      data-locations: classpath:./db/h2/data.sql

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework.security: debug
